// GENERATED by scripts/sync-prep-data.mjs — do not edit by hand.
import type { Problem } from '../types'

export const PACKS: Record<string, Problem> = {
 "dsa-001": {
  "id": "dsa-001",
  "slug": "contains-duplicate",
  "title": "Contains Duplicate",
  "difficulty": "Easy",
  "topic": "Arrays & Hashing",
  "link": "https://leetcode.com/problems/contains-duplicate/",
  "description_md": "Given an integer array, determine if any value shows up more than once.\n\n**Example:** for `[1, 2, 3, 1]`, the value `1` appears twice, so the answer is `true`. For `[1, 2, 3, 4]`, every value is unique, so the answer is `false`.\n\n**Constraints:** array length up to ~10^5, values can be any 32-bit integer (positive, negative, or zero).",
  "signature": {
   "name": "containsDuplicate",
   "params": [
    {
     "name": "nums",
     "kind": "value"
    }
   ],
   "returns": {
    "kind": "value"
   }
  },
  "starter_code": "def containsDuplicate(nums):\n    \"\"\"\n    nums: List[int]\n    Returns: bool\n    \"\"\"\n    pass\n",
  "reference_solution": "def containsDuplicate(nums):\n    hashset = set()\n    for n in nums:\n        if n in hashset:\n            return True\n        hashset.add(n)\n    return False\n",
  "solution_source": "https://github.com/neetcode-gh/leetcode/blob/main/python/0217-contains-duplicate.py",
  "compare": "exact",
  "tests": [
   {
    "input": [
     [
      1,
      2,
      3,
      1
     ]
    ],
    "expected": true,
    "kind": "example",
    "source": "https://leetcode.com/problems/contains-duplicate/ (problem statement example 1)"
   },
   {
    "input": [
     [
      1,
      2,
      3,
      4
     ]
    ],
    "expected": false,
    "kind": "example",
    "source": "https://leetcode.com/problems/contains-duplicate/ (problem statement example 2)"
   },
   {
    "input": [
     [
      1,
      1,
      1,
      3,
      3,
      4,
      3,
      2,
      4,
      2
     ]
    ],
    "expected": true,
    "kind": "example",
    "source": "https://leetcode.com/problems/contains-duplicate/ (problem statement example 3)"
   },
   {
    "input": [
     []
    ],
    "expected": false,
    "kind": "edge",
    "source": "derived: empty array has no duplicates"
   },
   {
    "input": [
     [
      7
     ]
    ],
    "expected": false,
    "kind": "edge",
    "source": "derived: single element cannot duplicate"
   },
   {
    "input": [
     [
      -1,
      -1
     ]
    ],
    "expected": true,
    "kind": "edge",
    "source": "derived: negative-number duplicate"
   }
  ]
 },
 "dsa-007": {
  "id": "dsa-007",
  "slug": "valid-sudoku",
  "title": "Valid Sudoku",
  "difficulty": "Medium",
  "topic": "Arrays & Hashing",
  "link": "https://leetcode.com/problems/valid-sudoku/",
  "description_md": "Given a partially filled 9x9 Sudoku board (as a grid of single-character strings, `.` marking an empty cell), decide if the digits placed so far are valid. Filled cells must satisfy the standard Sudoku rules: no digit repeats within any row, any column, or any of the nine 3x3 boxes. The board does not need to be solvable or complete -- only the cells already filled must be consistent.\n\n**Example:** a board where row 0 is `[\"5\",\"3\",\".\",\".\",\"7\",\".\",\".\",\".\",\".\"]` and the rest follow standard Sudoku layout with no repeated digit in any row/column/box returns `true`; if the same digit appears twice in one row it returns `false`.\n\n**Constraints:** board is always exactly 9x9; each cell is a digit `1`-`9` or `.`.",
  "signature": {
   "name": "isValidSudoku",
   "params": [
    {
     "name": "board",
     "kind": "value"
    }
   ],
   "returns": {
    "kind": "value"
   }
  },
  "starter_code": "def isValidSudoku(board):\n    \"\"\"\n    board: List[List[str]]  # 9x9 grid of single-char strings, '.' = empty\n    Returns: bool\n    \"\"\"\n    pass\n",
  "reference_solution": "import collections\n\ndef isValidSudoku(board):\n    cols = collections.defaultdict(set)\n    rows = collections.defaultdict(set)\n    squares = collections.defaultdict(set)  # key = (r // 3, c // 3)\n\n    for r in range(9):\n        for c in range(9):\n            if board[r][c] == '.':\n                continue\n            if (\n                board[r][c] in rows[r]\n                or board[r][c] in cols[c]\n                or board[r][c] in squares[(r // 3, c // 3)]\n            ):\n                return False\n            cols[c].add(board[r][c])\n            rows[r].add(board[r][c])\n            squares[(r // 3, c // 3)].add(board[r][c])\n    return True\n",
  "solution_source": "https://github.com/neetcode-gh/leetcode/blob/main/python/0036-valid-sudoku.py",
  "compare": "exact",
  "tests": [
   {
    "input": [
     [
      [
       "5",
       "3",
       ".",
       ".",
       "7",
       ".",
       ".",
       ".",
       "."
      ],
      [
       "6",
       ".",
       ".",
       "1",
       "9",
       "5",
       ".",
       ".",
       "."
      ],
      [
       ".",
       "9",
       "8",
       ".",
       ".",
       ".",
       ".",
       "6",
       "."
      ],
      [
       "8",
       ".",
       ".",
       ".",
       "6",
       ".",
       ".",
       ".",
       "3"
      ],
      [
       "4",
       ".",
       ".",
       "8",
       ".",
       "3",
       ".",
       ".",
       "1"
      ],
      [
       "7",
       ".",
       ".",
       ".",
       "2",
       ".",
       ".",
       ".",
       "6"
      ],
      [
       ".",
       "6",
       ".",
       ".",
       ".",
       ".",
       "2",
       "8",
       "."
      ],
      [
       ".",
       ".",
       ".",
       "4",
       "1",
       "9",
       ".",
       ".",
       "5"
      ],
      [
       ".",
       ".",
       ".",
       ".",
       "8",
       ".",
       ".",
       "7",
       "9"
      ]
     ]
    ],
    "expected": true,
    "kind": "example",
    "source": "https://leetcode.com/problems/valid-sudoku/ (problem statement example 1)"
   },
   {
    "input": [
     [
      [
       "8",
       "3",
       ".",
       ".",
       "7",
       ".",
       ".",
       ".",
       "."
      ],
      [
       "6",
       ".",
       ".",
       "1",
       "9",
       "5",
       ".",
       ".",
       "."
      ],
      [
       ".",
       "9",
       "8",
       ".",
       ".",
       ".",
       ".",
       "6",
       "."
      ],
      [
       "8",
       ".",
       ".",
       ".",
       "6",
       ".",
       ".",
       ".",
       "3"
      ],
      [
       "4",
       ".",
       ".",
       "8",
       ".",
       "3",
       ".",
       ".",
       "1"
      ],
      [
       "7",
       ".",
       ".",
       ".",
       "2",
       ".",
       ".",
       ".",
       "6"
      ],
      [
       ".",
       "6",
       ".",
       ".",
       ".",
       ".",
       "2",
       "8",
       "."
      ],
      [
       ".",
       ".",
       ".",
       "4",
       "1",
       "9",
       ".",
       ".",
       "5"
      ],
      [
       ".",
       ".",
       ".",
       ".",
       "8",
       ".",
       ".",
       "7",
       "9"
      ]
     ]
    ],
    "expected": false,
    "kind": "example",
    "source": "https://leetcode.com/problems/valid-sudoku/ (problem statement example 2: two 8s in column 0)"
   },
   {
    "input": [
     [
      [
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       "."
      ],
      [
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       "."
      ],
      [
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       "."
      ],
      [
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       "."
      ],
      [
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       "."
      ],
      [
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       "."
      ],
      [
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       "."
      ],
      [
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       "."
      ],
      [
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       "."
      ]
     ]
    ],
    "expected": true,
    "kind": "edge",
    "source": "derived: an entirely empty board is trivially valid"
   },
   {
    "input": [
     [
      [
       "1",
       "2",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       "."
      ],
      [
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       "."
      ],
      [
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       "."
      ],
      [
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       "."
      ],
      [
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       "."
      ],
      [
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       "."
      ],
      [
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       "."
      ],
      [
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       "."
      ],
      [
       ".",
       ".",
       ".",
       ".",
       ".",
       "1",
       ".",
       ".",
       "."
      ]
     ]
    ],
    "expected": true,
    "kind": "edge",
    "source": "derived: '1' appears twice but in different rows, columns, and 3x3 boxes -- valid"
   },
   {
    "input": [
     [
      [
       "1",
       "2",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       "."
      ],
      [
       ".",
       ".",
       "1",
       ".",
       ".",
       ".",
       ".",
       ".",
       "."
      ],
      [
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       "."
      ],
      [
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       "."
      ],
      [
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       "."
      ],
      [
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       "."
      ],
      [
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       "."
      ],
      [
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       "."
      ],
      [
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       ".",
       "."
      ]
     ]
    ],
    "expected": false,
    "kind": "edge",
    "source": "derived: duplicate '1' within the same top-left 3x3 box at (0,0) and (1,2)"
   }
  ]
 },
 "dsa-013": {
  "id": "dsa-013",
  "slug": "valid-palindrome",
  "title": "Valid Palindrome",
  "difficulty": "Easy",
  "topic": "Two Pointers",
  "link": "https://leetcode.com/problems/valid-palindrome/",
  "description_md": "Given a string, decide whether it reads the same forwards and backwards once you strip out everything except letters and digits and lowercase everything.\n\n**Example:** `\"A man, a plan, a canal: Panama\"` becomes `\"amanaplanacanalpanama\"` after cleaning, which is a palindrome, so the answer is `true`. `\"race a car\"` becomes `\"raceacar\"`, which is not a palindrome, so the answer is `false`.\n\n**Constraints:** string length up to ~10^5; may contain letters, digits, spaces, and punctuation.",
  "signature": {
   "name": "isPalindrome",
   "params": [
    {
     "name": "s",
     "kind": "value"
    }
   ],
   "returns": {
    "kind": "value"
   }
  },
  "starter_code": "def isPalindrome(s):\n    \"\"\"\n    s: str\n    Returns: bool\n    \"\"\"\n    pass\n",
  "reference_solution": "def isPalindrome(s):\n    new = ''\n    for a in s:\n        if a.isalpha() or a.isdigit():\n            new += a.lower()\n    return new == new[::-1]\n",
  "solution_source": "https://github.com/neetcode-gh/leetcode/blob/main/python/0125-valid-palindrome.py",
  "compare": "exact",
  "tests": [
   {
    "input": [
     "A man, a plan, a canal: Panama"
    ],
    "expected": true,
    "kind": "example",
    "source": "https://leetcode.com/problems/valid-palindrome/ (problem statement example 1)"
   },
   {
    "input": [
     "race a car"
    ],
    "expected": false,
    "kind": "example",
    "source": "https://leetcode.com/problems/valid-palindrome/ (problem statement example 2)"
   },
   {
    "input": [
     " "
    ],
    "expected": true,
    "kind": "example",
    "source": "https://leetcode.com/problems/valid-palindrome/ (problem statement example 3: empty after cleaning)"
   },
   {
    "input": [
     ""
    ],
    "expected": true,
    "kind": "edge",
    "source": "derived: empty string is a trivial palindrome"
   },
   {
    "input": [
     "a"
    ],
    "expected": true,
    "kind": "edge",
    "source": "derived: single character is always a palindrome"
   },
   {
    "input": [
     "0P"
    ],
    "expected": false,
    "kind": "edge",
    "source": "derived: alnum-mixed two-char non-palindrome, checks digit+letter handling"
   }
  ]
 },
 "dsa-019": {
  "id": "dsa-019",
  "slug": "longest-substring-without-repeating-characters",
  "title": "Longest Substring Without Repeating Characters",
  "difficulty": "Medium",
  "topic": "Sliding Window",
  "link": "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
  "description_md": "Given a string, find the length of the longest contiguous substring that has no repeated characters.\n\n**Example:** for `\"abcabcbb\"` the longest such substring is `\"abc\"`, length 3. For `\"bbbbb\"` it's `\"b\"`, length 1. For `\"pwwkew\"` it's `\"wke\"`, length 3 (note the substring doesn't need to be a prefix).\n\n**Constraints:** string length up to ~5*10^4; may contain letters, digits, symbols, and spaces.",
  "signature": {
   "name": "lengthOfLongestSubstring",
   "params": [
    {
     "name": "s",
     "kind": "value"
    }
   ],
   "returns": {
    "kind": "value"
   }
  },
  "starter_code": "def lengthOfLongestSubstring(s):\n    \"\"\"\n    s: str\n    Returns: int\n    \"\"\"\n    pass\n",
  "reference_solution": "def lengthOfLongestSubstring(s):\n    charSet = set()\n    l = 0\n    res = 0\n    for r in range(len(s)):\n        while s[r] in charSet:\n            charSet.remove(s[l])\n            l += 1\n        charSet.add(s[r])\n        res = max(res, r - l + 1)\n    return res\n",
  "solution_source": "https://github.com/neetcode-gh/leetcode/blob/main/python/0003-longest-substring-without-repeating-characters.py",
  "compare": "exact",
  "tests": [
   {
    "input": [
     "abcabcbb"
    ],
    "expected": 3,
    "kind": "example",
    "source": "https://leetcode.com/problems/longest-substring-without-repeating-characters/ (problem statement example 1)"
   },
   {
    "input": [
     "bbbbb"
    ],
    "expected": 1,
    "kind": "example",
    "source": "https://leetcode.com/problems/longest-substring-without-repeating-characters/ (problem statement example 2)"
   },
   {
    "input": [
     "pwwkew"
    ],
    "expected": 3,
    "kind": "example",
    "source": "https://leetcode.com/problems/longest-substring-without-repeating-characters/ (problem statement example 3)"
   },
   {
    "input": [
     ""
    ],
    "expected": 0,
    "kind": "edge",
    "source": "derived: empty string has no substrings"
   },
   {
    "input": [
     " "
    ],
    "expected": 1,
    "kind": "edge",
    "source": "derived: single space character, length 1"
   },
   {
    "input": [
     "dvdf"
    ],
    "expected": 3,
    "kind": "edge",
    "source": "derived: classic tricky case where the window must shrink past a repeated char that is not at the window start"
   }
  ]
 },
 "dsa-025": {
  "id": "dsa-025",
  "slug": "min-stack",
  "title": "Min Stack",
  "difficulty": "Medium",
  "topic": "Stack",
  "link": "https://leetcode.com/problems/min-stack/",
  "description_md": "Design a stack that supports the usual `push`/`pop`/`top` operations plus retrieving the minimum element currently on the stack, all in O(1) time.\n\n**Example:** push `-2`, `0`, `-3`; `getMin()` returns `-3`; `pop()` removes `-3`; `top()` returns `0`; `getMin()` now returns `-2`.\n\n**Constraints:** `pop`, `top`, and `getMin` are only ever called on a non-empty stack; values fit in a 32-bit signed integer.",
  "signature": {
   "name": "MinStack",
   "type": "class",
   "params": [],
   "returns": {
    "kind": "value"
   }
  },
  "starter_code": "class MinStack:\n    def __init__(self):\n        \"\"\"\n        Initializes an empty stack.\n        \"\"\"\n        pass\n\n    def push(self, val):\n        \"\"\"\n        val: int\n        Returns: None\n        \"\"\"\n        pass\n\n    def pop(self):\n        \"\"\"\n        Removes the top element. Returns: None\n        \"\"\"\n        pass\n\n    def top(self):\n        \"\"\"\n        Returns: int -- the top element.\n        \"\"\"\n        pass\n\n    def getMin(self):\n        \"\"\"\n        Returns: int -- the current minimum element on the stack.\n        \"\"\"\n        pass\n",
  "reference_solution": "class MinStack:\n    def __init__(self):\n        self.stack = []\n        self.minStack = []\n\n    def push(self, val):\n        self.stack.append(val)\n        val = min(val, self.minStack[-1] if self.minStack else val)\n        self.minStack.append(val)\n\n    def pop(self):\n        self.stack.pop()\n        self.minStack.pop()\n\n    def top(self):\n        return self.stack[-1]\n\n    def getMin(self):\n        return self.minStack[-1]\n",
  "solution_source": "https://github.com/neetcode-gh/leetcode/blob/main/python/0155-min-stack.py",
  "compare": "exact",
  "tests": [
   {
    "input": [
     [
      "MinStack",
      "push",
      "push",
      "push",
      "getMin",
      "pop",
      "top",
      "getMin"
     ],
     [
      [],
      [
       -2
      ],
      [
       0
      ],
      [
       -3
      ],
      [],
      [],
      [],
      []
     ]
    ],
    "expected": [
     null,
     null,
     null,
     null,
     -3,
     null,
     0,
     -2
    ],
    "kind": "example",
    "source": "https://leetcode.com/problems/min-stack/ (problem statement example 1)"
   },
   {
    "input": [
     [
      "MinStack",
      "push",
      "getMin",
      "push",
      "getMin",
      "pop",
      "getMin"
     ],
     [
      [],
      [
       1
      ],
      [],
      [
       2
      ],
      [],
      [],
      []
     ]
    ],
    "expected": [
     null,
     null,
     1,
     null,
     1,
     null,
     1
    ],
    "kind": "edge",
    "source": "derived: pushing a larger value after the min should not change getMin"
   },
   {
    "input": [
     [
      "MinStack",
      "push",
      "push",
      "push",
      "pop",
      "pop",
      "getMin"
     ],
     [
      [],
      [
       5
      ],
      [
       5
      ],
      [
       5
      ],
      [],
      [],
      []
     ]
    ],
    "expected": [
     null,
     null,
     null,
     null,
     null,
     null,
     5
    ],
    "kind": "edge",
    "source": "derived: duplicate equal values on the stack, min must survive pops correctly"
   },
   {
    "input": [
     [
      "MinStack",
      "push",
      "top",
      "getMin"
     ],
     [
      [],
      [
       0
      ],
      [],
      []
     ]
    ],
    "expected": [
     null,
     null,
     0,
     0
    ],
    "kind": "edge",
    "source": "derived: single-element stack, top and getMin agree"
   },
   {
    "input": [
     [
      "MinStack",
      "push",
      "push",
      "getMin",
      "pop",
      "getMin"
     ],
     [
      [],
      [
       -1
      ],
      [
       -2
      ],
      [],
      [],
      []
     ]
    ],
    "expected": [
     null,
     null,
     null,
     -2,
     null,
     -1
    ],
    "kind": "edge",
    "source": "derived: strictly decreasing negative pushes, min updates each push and reverts on pop"
   }
  ]
 }
}
